apiVersion: batch/v1
kind: Job
metadata:
  name: presync-cosign-verify
  namespace: gitops-demo
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 1800 # keep for 30 min
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cosign-verify
          image: ghcr.io/sigstore/cosign/cosign:v2.2.4
          args:
            - "verify"
            - "--certificate-oidc-issuer"
            - "https://token.actions.githubusercontent.com"
            - "--certificate-identity-regexp"
            - "https://github.com/UnpredictablePrashant/GitOpsDemoA/.+"
            - docker.io/prashantdey/gitops-demo-app@sha256:e9218789376b79074d5479b9dc6e0ae813af40d6673062124161d8aa1337871f
          env:
            - name: COSIGN_EXPERIMENTAL
              value: "true"
